title: "Raind Notes"
description: "自作コンテナランタイムの実装メモとセキュリティ検討"
lang: ja-JP

# Project Page
url: "https://pyxgun.github.io"
baseurl: "/raind-notes"

# Markdown
markdown: kramdown

# theme
plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
# favicon
favicon: true

# permalink
permalink: /:categories/:year/:month/:day/:title/

# build target
include:
  - docs

# timezone
timezone: Asia/Tokyo

## design customizing ##
# sidebar
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/pyxgun
